In [1]:
from read_di_unfccc import UNFCCCApiReader

## Using the unified query interface

In [2]:
# instantiate API object, will query metadata
r = UNFCCCApiReader()

In [3]:
# access metadata
r.parties

       code                name noData
id
3       AUS           Australia    NaN
4       AUT             Austria    NaN
5       BEL             Belgium    NaN
9       CAN              Canada    NaN
10      CHE         Switzerland    NaN
...     ...                 ...    ...
100214  VNM            Viet Nam    NaN
100215  YEM               Yemen    NaN
100216  ZMB              Zambia    NaN
100217  ZWE            Zimbabwe    NaN
100229  PSE  State of Palestine    NaN

[181 rows x 3 columns]

In [4]:
r.gases

                                   name
id
10466                 Aggregate F-gases
10467                    Aggregate GHGs
10468                               CH₄
10469                               CO₂
10470                              HFCs
10471                               N₂O
10472                               NF₃
10473                              PFCs
10474                               SF₆
10475  Unspecified mix of HFCs and PFCs
10601           Unspecified mix of HFCs
10602           Unspecified mix of PFCs
10603                            HFC-23
10604                            HFC-32
10605                            HFC-41
10606                      HFC-43-10mee
10607                           HFC-125
10608                           HFC-134
10609                          HFC-134a
10610                           HFC-143
10611                          HFC-143a
10612                           HFC-152
10613                          HFC-152a
10614                           HFC-161
10615                         HFC-227ea
10616                         HFC-236cb
10617                         HFC-236ea
10618                         HFC-236fa
10619                         HFC-245ca
10620                         HFC-245fa
10621                        HFC-365mfc
10622                               CF₄
10623                              C₂F₆
10624                            c-C₃F₆
10625                              C₃F₈
10626                            c-C₄F₈
10627                             C₄F₁₀
10628                             C5F₁₂
10629                             C₆F₁₄
10630                            C₁₀F₁₈
10631                                 C
10632                                CO
10633                               NH₃
10634                             NMVOC
10635                               NOₓ
10636                               SO₂
10637                            No gas

In [5]:
# for obtaining information from the database, use r.query()
r.query?

Signature:
r.query(
    *,
    party_code: str,
    gases: Union[List[str], NoneType] = None,
    progress: bool = False,
)
Docstring:
Query the UNFCCC for data.
:param party_code:       ISO codes of a party for which to query.
                         For possible values, see .parties .
:param gases:            list of gases to query for. For possible values, see .gases .
                         Default: query for all gases.
:param progress:         Display a progress bar. Requires tqdm.

If you need more fine-grained control over which variables to query for, including restricting the query
to specific measures, categories, or classifications or to query for multiple parties at once, please see the
corresponding methods .annex_one_reader.query and .non_annex_one_reader.query .
File:      ~/work/read_di_unfccc/read_di_unfccc.py
Type:      method

In [6]:
# Note that only the "party_code" parameter is mandatory, gases can be left empty to query for all gases
r.query(party_code='AFG')

,index,party,category,classification,measure,gas,unit,year,numberValue,stringValue
0,318,AFG,1. Energy,Total for category,Net emissions/removals,Aggregate GHGs,Gg CO₂ equivalent,2005,3776.15946,None
1,374,AFG,1. Energy,Total for category,Net emissions/removals,Aggregate GHGs,Gg CO₂ equivalent,2013,10281.00000,None
2,87,AFG,1. Energy,Total for category,Net emissions/removals,CH₄,Gg,2005,35.06076,None
3,173,AFG,1. Energy,Total for category,Net emissions/removals,CH₄,Gg,2013,4.00000,None
4,4,AFG,1. Energy,Total for category,Net emissions/removals,CO,Gg,2005,865.20000,None
...,...,...,...,...,...,...,...,...,...,...
373,242,AFG,unknown category nr. 10504,Total for category,Total population,No gas,thousands,2014,26556.75400,None
374,243,AFG,unknown category nr. 10504,Total for category,Total population,No gas,thousands,2015,27101.36500,None
375,244,AFG,unknown category nr. 10504,Total for category,Total population,No gas,thousands,2016,27657.14500,None
376,245,AFG,unknown category nr. 10504,Total for category,Total population,No gas,thousands,2017,28224.32300,None
377,246,AFG,unknown category nr. 10504,Total for category,Total population,No gas,thousands,2018,30075.01800,None

In [7]:
# the result is returned in a pandas DataFrame. Note that sometimes, unknown categories are returned (ex. "unkown category nr. 10503") and
# data points can have a numberValue and/or a stringValue such as "NO", "NE", or "C"

In [8]:
# Querying Annex-I parties for all gases leads to large queries which take a relatively long time to process
r.query(party_code='DEU')

,index,party,category,classification,measure,gas,unit,year,numberValue,stringValue
0,63671,DEU,1. Energy,Total for category,Emission factor information,CH₄,no unit,1990,NaN,"CS,D,M"
1,63672,DEU,1. Energy,Total for category,Emission factor information,CH₄,no unit,1991,NaN,"CS,D,M"
2,63673,DEU,1. Energy,Total for category,Emission factor information,CH₄,no unit,1992,NaN,"CS,D,M"
3,63674,DEU,1. Energy,Total for category,Emission factor information,CH₄,no unit,1993,NaN,"CS,D,M"
4,63675,DEU,1. Energy,Total for category,Emission factor information,CH₄,no unit,1994,NaN,"CS,D,M"
...,...,...,...,...,...,...,...,...,...,...
309607,50136,DEU,unknown category nr. 10504,Total for category,Total population,No gas,thousands,2015,81686.6630,None
309608,50137,DEU,unknown category nr. 10504,Total for category,Total population,No gas,thousands,2016,82348.6685,None
309609,50138,DEU,unknown category nr. 10504,Total for category,Total population,No gas,thousands,2017,82657.0020,None
309610,50139,DEU,unknown category nr. 10504,Total for category,Total population,No gas,thousands,2018,82792.3510,None
309611,50110,DEU,unknown category nr. 10504,Total for category,Total population,No gas,thousands,Base year,79364.5040,None

In [9]:
# If you don't need all the information, it is beneficial to query for single gases only
# or use the more specialized query interface (see below)
r.query(party_code='DEU', gases=['N₂O'])

,index,party,category,classification,measure,gas,unit,year,numberValue,stringValue
0,8131,DEU,1. Energy,Total for category,Emission factor information,N₂O,no unit,1990,NaN,"CS,D,M"
1,8132,DEU,1. Energy,Total for category,Emission factor information,N₂O,no unit,1991,NaN,"CS,D,M"
2,8133,DEU,1. Energy,Total for category,Emission factor information,N₂O,no unit,1992,NaN,"CS,D,M"
3,8134,DEU,1. Energy,Total for category,Emission factor information,N₂O,no unit,1993,NaN,"CS,D,M"
4,8135,DEU,1. Energy,Total for category,Emission factor information,N₂O,no unit,1994,NaN,"CS,D,M"
...,...,...,...,...,...,...,...,...,...,...
34168,86,DEU,Total GHG emissions without LULUCF,Total for category,Net emissions/removals,N₂O,kt,2015,129.755265,None
34169,87,DEU,Total GHG emissions without LULUCF,Total for category,Net emissions/removals,N₂O,kt,2016,126.960736,None
34170,88,DEU,Total GHG emissions without LULUCF,Total for category,Net emissions/removals,N₂O,kt,2017,125.976196,None
34171,89,DEU,Total GHG emissions without LULUCF,Total for category,Net emissions/removals,N₂O,kt,2018,119.188881,None
34172,60,DEU,Total GHG emissions without LULUCF,Total for category,Net emissions/removals,N₂O,kt,Base year,209.808203,None

## Using the specialized query interfaces for finer control

In [10]:
# API objects for annexOne and nonAnnexOne parties are available
r.annex_one_reader
r.non_annex_one_reader

In [11]:
# access metadata
r.annex_one_reader.parties

   code                                               name
id
3   AUS                                          Australia
4   AUT                                            Austria
5   BEL                                            Belgium
9   CAN                                             Canada
10  CHE                                        Switzerland
11  CYP                                             Cyprus
13  DEU                                            Germany
15  DNK                                            Denmark
17  ESP                                              Spain
21  FIN                                            Finland
23  FRA                                             France
27  GBR  United Kingdom of Great Britain and Northern I...
28  GRC                                             Greece
32  IRL                                            Ireland
33  ISL                                            Iceland
34  ITA                                              Italy
35  JPN                                              Japan
38  LIE                                      Liechtenstein
40  LUX                                         Luxembourg
42  MCO                                             Monaco
43  MLT                                              Malta
44  NLD                                        Netherlands
45  NOR                                             Norway
46  NZL                                        New Zealand
48  PRT                                           Portugal
53  SWE                                             Sweden
54  TUR                                             Turkey
56  USA                           United States of America

In [12]:
# other available metadata
#r.annex_one_reader.years
#r.annex_one_reader.classifications
#r.annex_one_reader.gases
#r.annex_one_reader.units
#r.annex_one_reader.conversion_factors

In [13]:
# categories and measures are available in hierarchies
#r.annex_one_reader.category_tree
#r.annex_one_reader.measure_tree

# for easier viewing, use the associated methods; note the id in brackets that you need if you want to query for a specific category/measure
#r.annex_one_reader.show_measure_hierarchy()
r.annex_one_reader.show_category_hierarchy()

Totals[10465]
├── Total GHG emissions with LULUCF[8677]
│   ├── 1.  Energy[8819]
│   │   ├── 1.AA  Fuel Combustion - Sectoral approach[9089]
│   │   │   ├── 1.A.1  Energy Industries[10402]
│   │   │   │   ├── 1.A.1.a  Public Electricity and Heat Production[9422]
│   │   │   │   │   ├── 1.A.1.a.i  Electricity Generation[8616]
│   │   │   │   │   ├── 1.A.1.a.ii  Combined Heat and Power Generation[9614]
│   │   │   │   │   ├── 1.A.1.a.iii  Heat Plants[9971]
│   │   │   │   │   └── 1.A.1.a.iv  Other[8368]
│   │   │   │   ├── 1.A.1.b  Petroleum Refining[9771]
│   │   │   │   └── 1.A.1.c  Manufacture of Solid Fuels and Other Energy Industries[9004]
│   │   │   │       ├── 1.A.1.c.i  Manufacture of Solid Fuels[10306]
│   │   │   │       ├── 1.A.1.c.ii  Oil and Gas Extraction[10425]
│   │   │   │       ├── 1.A.1.c.iii  Other Energy Industries[8335]
│   │   │   │       └── 1.A.1.c.iv  Other[8656]
│   │   │   ├── 1.A.2  Manufacturing Industries and Construction[8556]
│   │   │   │   ├── 1.A.2.a  Iron and Steel[10329]
│   │   │   │   ├── 1.A.2.b  Non-Ferrous Metals[9859]
│   │   │   │   ├── 1.A.2.c  Chemicals[9369]
│   │   │   │   ├── 1.A.2.d  Pulp, Paper and Print[10119]
│   │   │   │   ├── 1.A.2.e  Food Processing, Beverages and Tobacco[8321]
│   │   │   │   ├── 1.A.2.f  Non-metallic Minerals[8876]
│   │   │   │   └── 1.A.2.g  Other[9832]
│   │   │   │       ├── 1.A.2.g.i  Manufacturing of Machinery[10308]
│   │   │   │       ├── 1.A.2.g.ii  Manufacturing of Transport Equipment[10150]
│   │   │   │       ├── 1.A.2.g.iii  Mining (Excluding Fuels) and Quarrying[8527]
│   │   │   │       ├── 1.A.2.g.iv  Wood and Wood Products[8424]
│   │   │   │       ├── 1.A.2.g.v  Construction[10287]
│   │   │   │       ├── 1.A.2.g.vi  Textile and Leather[8721]
│   │   │   │       ├── 1.A.2.g.vii  Off-road Vehicles and Other Machinery[8587]
│   │   │   │       └── 1.A.2.g.viii  Other[8794]
│   │   │   ├── 1.A.3  Transport[8322]
│   │   │   │   ├── 1.A.3.a  Domestic Aviation[10419]
│   │   │   │   ├── 1.A.3.b  Road Transportation[9607]
│   │   │   │   │   ├── 1.A.3.b.i  Cars[9279]
│   │   │   │   │   ├── 1.A.3.b.ii  Light Duty Trucks[9702]
│   │   │   │   │   ├── 1.A.3.b.iii  Heavy Duty Trucks and Buses[8358]
│   │   │   │   │   ├── 1.A.3.b.iv  Motorcycles[9622]
│   │   │   │   │   └── 1.A.3.b.v  Other[9083]
│   │   │   │   ├── 1.A.3.c  Railways[8924]
│   │   │   │   ├── 1.A.3.d  Domestic Navigation[9670]
│   │   │   │   └── 1.A.3.e  Other Transportation[8456]
│   │   │   │       ├── 1.A.3.e.i  Pipeline Transport[9504]
│   │   │   │       └── 1.A.3.e.ii  Other[9935]
│   │   │   ├── 1.A.4  Other Sectors[9815]
│   │   │   │   ├── 1.A.4.a  Commercial/Institutional[8597]
│   │   │   │   │   ├── 1.A.4.a.i  Stationary Combustion[8216]
│   │   │   │   │   ├── 1.A.4.a.ii  Off-road Vehicles and Other Machinery[8251]
│   │   │   │   │   └── 1.A.4.a.iii  Other[8223]
│   │   │   │   ├── 1.A.4.b  Residential[9823]
│   │   │   │   │   ├── 1.A.4.b.i  Stationary Combustion[8609]
│   │   │   │   │   ├── 1.A.4.b.ii  Off-road Vehicles and Other Machinery[10435]
│   │   │   │   │   └── 1.A.4.b.iii  Other[8632]
│   │   │   │   └── 1.A.4.c  Agriculture/Forestry/Fishing[8554]
│   │   │   │       ├── 1.A.4.c.i  Stationary[8364]
│   │   │   │       ├── 1.A.4.c.ii  Off-road Vehicles and Other Machinery[10080]
│   │   │   │       └── 1.A.4.c.iii  Fishing[9812]
│   │   │   ├── 1.A.5  Other (Not specified elsewhere)[10273]
│   │   │   │   ├── 1.A.5.a  Stationary[9861]
│   │   │   │   └── 1.A.5.b  Mobile[9101]
│   │   │   └── Information Item[11026]
│   │   │       ├── Waste Incineration with Energy Recovery included as Biomass[11027]
│   │   │       └── Waste Incineration with Energy Recovery included as Fossil Fuels[11028]
│   │   ├── 1.AB  Fuel Combustion - Reference Approach[8533]
│   │   ├── 1.AD  Feedstocks, Reductants and Other Non-energy Use of Fuels[8731]
│   │   ├── 1.B  Fugitive Emissions from Fuels[9374]
│   │   │   ├── 1.B.1  Solid Fuels[9455]
│   │   │   │   ├── 1.B.1.a  Coal Mining and Handling[9835]
│   │   │   │   │   ├── 1.B.1.a.i  Underground Mines[9116]
│   │   │   │   │   │   ├── 1.B.1.a.i.1  Mining Activities[9933]
│   │   │   │   │   │   ├── 1.B.1.a.i.2  Post-Mining Activities[9427]
│   │   │   │   │   │   └── 1.B.1.a.i.3  Abandoned Underground Mines[8211]
│   │   │   │   │   └── 1.B.1.a.ii  Surface Mines[8573]
│   │   │   │   │       ├── 1.B.1.a.ii.1  Mining Activities[10282]
│   │   │   │   │       └── 1.B.1.a.ii.2  Post-Mining Activities[9601]
│   │   │   │   ├── 1.B.1.b  Solid Fuel Transformation[8300]
│   │   │   │   └── 1.B.1.c  Other[8964]
│   │   │   └── 1.B.2  Oil and Natural Gas and Other Emissions from Energy Production[8806]
│   │   │       ├── 1.B.2.a  Oil[9822]
│   │   │       │   ├── 1.B.2.a.i  Exploration[8165]
│   │   │       │   ├── 1.B.2.a.ii  Production[10078]
│   │   │       │   ├── 1.B.2.a.iii  Transport[9550]
│   │   │       │   ├── 1.B.2.a.iv  Refining / Storage[9891]
│   │   │       │   ├── 1.B.2.a.v  Distribution of Oil Products[8371]
│   │   │       │   └── 1.B.2.a.vi  Other[8228]
│   │   │       ├── 1.B.2.b  Natural Gas[8493]
│   │   │       │   ├── 1.B.2.b.i  Exploration[9314]
│   │   │       │   ├── 1.B.2.b.ii  Production[8474]
│   │   │       │   ├── 1.B.2.b.iii  Processing[9999]
│   │   │       │   ├── 1.B.2.b.iv  Transmission and Storage[9902]
│   │   │       │   ├── 1.B.2.b.v  Distribution[9728]
│   │   │       │   └── 1.B.2.b.vi  Other[9974]
│   │   │       ├── 1.B.2.c  Venting and Flaring[8333]
│   │   │       │   ├── 1.B.2.c.i  Venting[10303]
│   │   │       │   │   ├── 1.B.2.c.i.1  Oil[9827]
│   │   │       │   │   ├── 1.B.2.c.i.2  Gas[10239]
│   │   │       │   │   └── 1.B.2.c.i.3  Combined[8576]
│   │   │       │   └── 1.B.2.c.ii  Flaring[10392]
│   │   │       │       ├── 1.B.2.c.ii.1  Oil[9210]
│   │   │       │       ├── 1.B.2.c.ii.2  Gas[8904]
│   │   │       │       └── 1.B.2.c.ii.3  Combined[9824]
│   │   │       └── 1.B.2.d  Other[9077]
│   │   ├── 1.C  CO₂ Transport and Storage[9070]
│   │   │   ├── 1.C.1  Transport of CO₂[9365]
│   │   │   │   ├── 1.C.1.a  Pipelines[9769]
│   │   │   │   ├── 1.C.1.b  Ships[10197]
│   │   │   │   └── 1.C.1.c  Other[9366]
│   │   │   ├── 1.C.2  Injection and Storage[9474]
│   │   │   │   ├── 1.C.2.a  Injection[8741]
│   │   │   │   └── 1.C.2.b  Storage[10333]
│   │   │   ├── 1.C.3  Other[9330]
│   │   │   └── Information Item[11029]
│   │   │       ├── Total Amount Captured for Storage[11030]
│   │   │       ├── Total Amount of CO₂ Injected at Storage Sites[11033]
│   │   │       ├── Total Amount of Exports for Storage[11032]
│   │   │       ├── Total Amount of Imports for Storage[11031]
│   │   │       └── Total Leakage from Transport, Injection and Storage[11034]
│   │   └── Memo Items[8869]
│   │       ├── CO₂ Emissions from Biomass[8270]
│   │       ├── International Bunkers[8564]
│   │       │   ├── International Aviation[10357]
│   │       │   └── International Navigation[8828]
│   │       └── Multilateral Operations[8987]
│   ├── 2.  Industrial Processes and Product Use[10393]
│   │   ├── 2.A  Mineral Industry[8452]
│   │   │   ├── 2.A.1  Cement Production[8787]
│   │   │   ├── 2.A.2  Lime Production[8702]
│   │   │   ├── 2.A.3  Glass production[8579]
│   │   │   └── 2.A.4  Other Process Uses of Carbonates[9731]
│   │   │       ├── 2.A.4.a  Ceramics[8539]
│   │   │       ├── 2.A.4.b  Other Uses of Soda Ash[9452]
│   │   │       ├── 2.A.4.c  Non-metallurgical Magnesium Production[10101]
│   │   │       └── 2.A.4.d  Other[9342]
│   │   ├── 2.B  Chemical Industry[9304]
│   │   │   ├── 2.B.1  Ammonia Production[9658]
│   │   │   ├── 2.B.10  Other[9953]
│   │   │   ├── 2.B.2  Nitric Acid Production[9410]
│   │   │   ├── 2.B.3  Adipic Acid Production[8468]
│   │   │   ├── 2.B.4  Caprolactam, Glyoxal and Glyoxylic Acid Production[8544]
│   │   │   │   ├── 2.B.4.a  Caprolactam[9515]
│   │   │   │   ├── 2.B.4.b  Glyoxal[9564]
│   │   │   │   └── 2.B.4.c  Glyoxylic Acid[8789]
│   │   │   ├── 2.B.5  Carbide Production[9531]
│   │   │   │   ├── 2.B.5.a  Silicon Carbide[9683]
│   │   │   │   └── 2.B.5.b  Calcium Carbide[9206]
│   │   │   ├── 2.B.6  Titanium Dioxide Production[9917]
│   │   │   ├── 2.B.7  Soda Ash Production[8530]
│   │   │   ├── 2.B.8  Petrochemical and Carbon Black Production[9000]
│   │   │   │   ├── 2.B.8.a  Methanol[8934]
│   │   │   │   ├── 2.B.8.b  Ethylene[9146]
│   │   │   │   ├── 2.B.8.c  Ethylene Dichloride and Vinyl Chloride Monomer[8686]
│   │   │   │   ├── 2.B.8.d  Ethylene Oxide[9468]
│   │   │   │   ├── 2.B.8.e  Acrylonitrile[9784]
│   │   │   │   ├── 2.B.8.f  Carbon Black[8864]
│   │   │   │   └── 2.B.8.g  Other[9384]
│   │   │   │       ├── 2.B.8.g.i  Styrene[9941]
│   │   │   │       └── 2.B.8.g.ii  Other[8276]
│   │   │   └── 2.B.9  Fluorochemical Production[8884]
│   │   │       ├── 2.B.9.a  By-Product Emissions[9517]
│   │   │       │   ├── 2.B.9.a.i  Production of HCFC-22[9992]
│   │   │       │   └── 2.B.9.a.ii  Other[8782]
│   │   │       └── 2.B.9.b  Fugitive Emissions[9938]
│   │   │           ├── 2.B.9.b.i  Production of HFC-134a[8427]
│   │   │           ├── 2.B.9.b.ii  Production of SF₆[8150]
│   │   │           └── 2.B.9.b.iii  Other[8419]
│   │   ├── 2.C  Metal Industry[9064]
│   │   │   ├── 2.C.1  Iron and Steel Production[8229]
│   │   │   │   ├── 2.C.1.a  Steel[9540]
│   │   │   │   ├── 2.C.1.b  Pig Iron[9567]
│   │   │   │   ├── 2.C.1.c  Direct Reduced Iron[9679]
│   │   │   │   ├── 2.C.1.d  Sinter[8962]
│   │   │   │   ├── 2.C.1.e  Pellet[9387]
│   │   │   │   └── 2.C.1.f  Other[10223]
│   │   │   ├── 2.C.2  Ferroalloys Production[10390]
│   │   │   ├── 2.C.3  Aluminium Production[10068]
│   │   │   │   ├── 2.C.3.a  CO₂ Emissions[9079]
│   │   │   │   ├── 2.C.3.b  By-Product Emissions[9445]
│   │   │   │   └── 2.C.3.c  F-gases Used in Foundries[9072]
│   │   │   ├── 2.C.4  Magnesium Production[9635]
│   │   │   ├── 2.C.5  Lead Production[10210]
│   │   │   ├── 2.C.6  Zinc Production[9667]
│   │   │   └── 2.C.7  Other[10447]
│   │   ├── 2.D  Non-energy Products from Fuels and Solvent Use[10094]
│   │   │   ├── 2.D.1  Lubricant Use[8852]
│   │   │   ├── 2.D.2  Paraffin Wax Use[8925]
│   │   │   └── 2.D.3  Other[8811]
│   │   │       ├── 2.D.3.a  Solvent Use[10214]
│   │   │       ├── 2.D.3.b  Road Paving with Asphalt[10044]
│   │   │       ├── 2.D.3.c  Asphalt Roofing[8822]
│   │   │       └── 2.D.3.d  Other[8212]
│   │   ├── 2.E  Electronics Industry[8938]
│   │   │   ├── 2.E.1  Integrated Circuit or Semiconductor[10075]
│   │   │   ├── 2.E.2  TFT Flat Panel Display[10442]
│   │   │   ├── 2.E.3  Photovoltaics[8601]
│   │   │   ├── 2.E.4  Heat Transfer Fluid[9911]
│   │   │   └── 2.E.5  Other[8434]
│   │   ├── 2.F  Product Uses as Substitutes for ODS[8262]
│   │   │   ├── 2.F.1  Refrigeration and Air-conditioning[9207]
│   │   │   │   ├── 2.F.1.a  Commercial Refrigeration[9129]
│   │   │   │   ├── 2.F.1.b  Domestic Refrigeration[9780]
│   │   │   │   ├── 2.F.1.c  Industrial Refrigeration[10252]
│   │   │   │   ├── 2.F.1.d  Transport Refrigeration[9634]
│   │   │   │   ├── 2.F.1.e  Mobile Air-conditioning[10244]
│   │   │   │   └── 2.F.1.f  Stationary Air-conditioning[10298]
│   │   │   ├── 2.F.2  Foam Blowing Agents[9352]
│   │   │   │   ├── 2.F.2.a  Closed Cells[8642]
│   │   │   │   └── 2.F.2.b  Open Cells[9224]
│   │   │   ├── 2.F.3  Fire Protection[9296]
│   │   │   ├── 2.F.4  Aerosols[10383]
│   │   │   │   ├── 2.F.4.a  Metered Dose Inhalers[8519]
│   │   │   │   └── 2.F.4.b  Other[8379]
│   │   │   ├── 2.F.5  Solvents[8316]
│   │   │   └── 2.F.6  Other Applications[8607]
│   │   │       ├── 2.F.6.a  Emissive[10246]
│   │   │       └── 2.F.6.b  Contained[10042]
│   │   ├── 2.G  Other Product Manufacture and Use[8201]
│   │   │   ├── 2.G.1  Electrical Equipment[9490]
│   │   │   ├── 2.G.2  SF₆ and PFCs from Other Product Use[10301]
│   │   │   │   ├── 2.G.2.a  Military Applications[9055]
│   │   │   │   ├── 2.G.2.b  Accelerators[9925]
│   │   │   │   ├── 2.G.2.c  Soundproof Windows[9789]
│   │   │   │   ├── 2.G.2.d  Adiabatic Properties: Shoes and Tyres[9610]
│   │   │   │   └── 2.G.2.e  Other[8978]
│   │   │   ├── 2.G.3  N₂O from Product Uses[10433]
│   │   │   │   ├── 2.G.3.a  Medical Applications[8737]
│   │   │   │   └── 2.G.3.b  Other[9014]
│   │   │   │       ├── 2.G.3.b.i  Propellant for Pressure and Aerosol Products[9201]
│   │   │   │       └── 2.G.3.b.ii  Other[8566]
│   │   │   └── 2.G.4  Other[8534]
│   │   └── 2.H  Other[9899]
│   │       ├── 2.H.1  Pulp and Paper[8644]
│   │       ├── 2.H.2  Food and Beverages Industry[8797]
│   │       └── 2.H.3  Other[8883]
│   ├── 3.  Agriculture[10096]
│   │   ├── 3.A  Enteric Fermentation[9559]
│   │   ├── 3.B  Manure Management[9608]
│   │   ├── 3.C  Rice Cultivation[10228]
│   │   │   ├── 3.C.1  Irrigated[9960]
│   │   │   │   ├── 3.C.1.a  Continuously Flooded[10315]
│   │   │   │   └── 3.C.1.b  Intermittently Flooded[8915]
│   │   │   │       ├── 3.C.1.b.i  Single Aeration[9184]
│   │   │   │       └── 3.C.1.b.ii  Multiple Aeration[10065]
│   │   │   ├── 3.C.2  Rainfed[8984]
│   │   │   │   ├── 3.C.2.a  Flood Prone[9942]
│   │   │   │   └── 3.C.2.b  Drought Prone[8941]
│   │   │   ├── 3.C.3  Deep Water[9094]
│   │   │   │   ├── 3.C.3.a  Water Depth 50-100 cm[8995]
│   │   │   │   └── 3.C.3.b  Water Depth > 100 cm[8373]
│   │   │   └── 3.C.4  Other[8747]
│   │   ├── 3.D  Agricultural Soils[9678]
│   │   │   ├── 3.D.1  Direct N₂O Emissions From Managed Soils[9087]
│   │   │   │   ├── 3.D.1.a  Inorganic N Fertilizers[9566]
│   │   │   │   ├── 3.D.1.b  Organic N Fertilizers[9523]
│   │   │   │   │   ├── 3.D.1.b.i  Animal Manure Applied to Soils[8365]
│   │   │   │   │   ├── 3.D.1.b.ii  Sewage Sludge Applied to Soils[8482]
│   │   │   │   │   └── 3.D.1.b.iii  Other Organic Fertilizers Applied to Soils[8218]
│   │   │   │   ├── 3.D.1.c  Urine and Dung Deposited by Grazing Animals[9041]
│   │   │   │   ├── 3.D.1.d  Crop Residues[10142]
│   │   │   │   ├── 3.D.1.e  Mineralization/Immobilization Associated with Loss/Gain of Soil Organic Matter[9302]
│   │   │   │   ├── 3.D.1.f  Cultivation of Organic Soils[10437]
│   │   │   │   └── 3.D.1.g  Other[8502]
│   │   │   └── 3.D.2  Indirect N₂O Emissions From Managed Soils[8920]
│   │   │       ├── 3.D.2.a  Atmospheric Deposition[9821]
│   │   │       └── 3.D.2.b  Nitrogen Leaching and Run-off[9875]
│   │   ├── 3.E  Prescribed Burning of Savannas[10322]
│   │   │   ├── 3.E.1  Forest Land[9488]
│   │   │   └── 3.E.2  Grassland[9970]
│   │   ├── 3.F  Field Burning of Agricultural Residues[8783]
│   │   │   ├── 3.F.1  Cereals[10305]
│   │   │   │   ├── 3.F.1.a  Wheat[8669]
│   │   │   │   ├── 3.F.1.b  Barley[10193]
│   │   │   │   ├── 3.F.1.c  Maize[8990]
│   │   │   │   └── 3.F.1.d  Other[9507]
│   │   │   ├── 3.F.2  Pulses[9749]
│   │   │   ├── 3.F.3  Tubers and Roots[9142]
│   │   │   ├── 3.F.4  Sugar Cane[10387]
│   │   │   └── 3.F.5  Other[10336]
│   │   ├── 3.G  Liming[8278]
│   │   │   ├── 3.G.1  Limestone CaCO₃[8504]
│   │   │   └── 3.G.2  Dolomite CaMg(CO₃)₂[8267]
│   │   ├── 3.H  Urea Application[9927]
│   │   ├── 3.I  Other Carbon-containing Fertilizers[8417]
│   │   └── 3.J  Other[10025]
│   ├── 4.  Land Use, Land-Use Change and Forestry[9411]
│   │   ├── 4.A  Forest Land[10121]
│   │   │   ├── 4.A.1  Forest Land Remaining Forest Land[8348]
│   │   │   └── 4.A.2  Land Converted to Forest Land[8416]
│   │   │       ├── 4.A.2.a  Cropland Converted to Forest Land[9741]
│   │   │       ├── 4.A.2.b  Grassland Converted to Forest Land[9851]
│   │   │       ├── 4.A.2.c  Wetlands Converted to Forest Land[9306]
│   │   │       ├── 4.A.2.d  Settlements Converted to Forest Land[10297]
│   │   │       └── 4.A.2.e  Other Land Converted to Forest Land[8735]
│   │   ├── 4.B  Cropland[9805]
│   │   │   ├── 4.B.1  Cropland Remaining Cropland[10430]
│   │   │   └── 4.B.2  Land Converted to Cropland[8678]
│   │   │       ├── 4.B.2.a  Forest Land Converted to Cropland[9799]
│   │   │       ├── 4.B.2.b  Grassland Converted to Cropland[9491]
│   │   │       ├── 4.B.2.c  Wetlands Converted to Cropland[10450]
│   │   │       ├── 4.B.2.d  Settlements Converted to Cropland[8709]
│   │   │       └── 4.B.2.e  Other Land Converted to Cropland[9560]
│   │   ├── 4.C  Grassland[8849]
│   │   │   ├── 4.C.1  Grassland Remaining Grassland[9360]
│   │   │   └── 4.C.2  Land Converted to Grassland[8259]
│   │   │       ├── 4.C.2.a  Forest Land Converted to Grassland[9405]
│   │   │       ├── 4.C.2.b  Cropland Converted to Grassland[9966]
│   │   │       ├── 4.C.2.c  Wetlands Converted to Grassland[10323]
│   │   │       ├── 4.C.2.d  Settlements Converted to Grassland[9444]
│   │   │       └── 4.C.2.e  Other Land Converted to Grassland[10189]
│   │   ├── 4.D  Wetlands[9897]
│   │   │   ├── 4.D.1  Wetlands Remaining Wetlands[9154]
│   │   │   │   ├── 4.D.1.a  Peat Extraction Remaining Peat Extraction[10156]
│   │   │   │   ├── 4.D.1.b  Flooded Land Remaining Flooded Land[9151]
│   │   │   │   └── 4.D.1.c  Other Wetlands Remaining Other Wetlands[8307]
│   │   │   └── 4.D.2  Land Converted to Wetlands[8232]
│   │   │       ├── 4.D.2.a  Land Converted to Peat Extraction[11002]
│   │   │       ├── 4.D.2.b  Land Converted to Flooded Land[11003]
│   │   │       │   ├── 4.D.2.b.i  Forest Land Converted to Flooded Land[11004]
│   │   │       │   ├── 4.D.2.b.ii  Cropland Converted to Flooded Land[11005]
│   │   │       │   ├── 4.D.2.b.iii  Grassland Converted to Flooded Land[11006]
│   │   │       │   ├── 4.D.2.b.iv  Settlements Converted to Flooded Land[11007]
│   │   │       │   └── 4.D.2.b.v  Other Land Converted to Flooded Land[11008]
│   │   │       └── 4.D.2.c  Land Converted to Other Wetlands[11009]
│   │   │           ├── 4.D.2.c.i  Forest Land Converted to Other Wetlands[11010]
│   │   │           ├── 4.D.2.c.ii  Cropland Converted to Other Wetlands[11011]
│   │   │           ├── 4.D.2.c.iii  Grassland Converted to Other Wetlands[11012]
│   │   │           ├── 4.D.2.c.iv  Settlements Converted to Other Wetlands[11013]
│   │   │           └── 4.D.2.c.v  Other Land Converted to Other Wetlands[11014]
│   │   ├── 4.E  Settlements[10314]
│   │   │   ├── 4.E.1  Settlements Remaining Settlements[10132]
│   │   │   └── 4.E.2  Land Converted to Settlements[9506]
│   │   │       ├── 4.E.2.a  Forest Land Converted to Settlements[10183]
│   │   │       ├── 4.E.2.b  Cropland Converted to Settlements[9914]
│   │   │       ├── 4.E.2.c  Grassland Converted to Settlements[10026]
│   │   │       ├── 4.E.2.d  Wetlands Converted to Settlements[8465]
│   │   │       └── 4.E.2.e  Other Land Converted to Settlements[9857]
│   │   ├── 4.F  Other Land[8288]
│   │   │   ├── 4.F.1  Other Land Remaining Other Land[11015]
│   │   │   └── 4.F.2  Land Converted to Other Land[8343]
│   │   │       ├── 4.F.2.a  Forest Land Converted to Other Land[8488]
│   │   │       ├── 4.F.2.b  Cropland Converted to Other Land[8234]
│   │   │       ├── 4.F.2.c  Grassland Converted  to Other Land[8574]
│   │   │       ├── 4.F.2.d  Wetlands Converted to Other Land[10371]
│   │   │       └── 4.F.2.e  Settlements Converted to Other Land[9019]
│   │   ├── 4.G  Harvested Wood Products[9133]
│   │   │   ├── 4.G.1  Solid Wood[11016]
│   │   │   │   ├── 4.G.1.a  Sawnwood[11017]
│   │   │   │   ├── 4.G.1.b  Wood Panels[11018]
│   │   │   │   └── 4.G.1.c  Other Solid Wood Products[11019]
│   │   │   ├── 4.G.2  Paper and Paperboard[11020]
│   │   │   ├── 4.G.3  Other[11021]
│   │   │   └── Information Item[11035]
│   │   │       └── HWP in SWDS[11036]
│   │   └── 4.H  Other[9158]
│   ├── 5.  Waste[10159]
│   │   ├── 5.A  Solid Waste Disposal[9284]
│   │   │   ├── 5.A.1  Managed Waste Disposal Sites[8477]
│   │   │   │   ├── 5.A.1.a  Anaerobic[9839]
│   │   │   │   └── 5.A.1.b  Semi-aerobic[9144]
│   │   │   ├── 5.A.2  Unmanaged Waste Disposal Sites[10235]
│   │   │   └── 5.A.3  Uncategorized Waste Disposal Sites[8652]
│   │   ├── 5.B  Biological Treatment of Solid Waste[9245]
│   │   │   ├── 5.B.1  Composting[8701]

In [14]:
# for obtaining information from the database, use query()
r.annex_one_reader.query?

Signature:
r.annex_one_reader.query(
    *,
    party_codes: List[str],
    category_ids: Union[NoneType, List[int]] = None,
    classifications: Union[NoneType, List[str]] = None,
    measure_ids: Union[NoneType, List[int]] = None,
    gases: Union[NoneType, List[str]] = None,
    batch_size: int = 1000,
    progress: bool = False,
) -> pandas.core.frame.DataFrame
Docstring:
Query the UNFCCC for data.
:param party_codes:      list of ISO codes of the parties to query.
                         For possible values, see .parties .
:param category_ids:     list of category IDs to query. For possible values, see .show_category_hierarchy().
                         Default: query for all categories.
:param classifications:  list of classifications to query. For possible values, see .classifications .
                         Default: query for all classifications.
:param measure_ids:      list of measure IDs to query. For possible values, see .show_measure_hierarchy().
                         Default: query for all measures.
:param gases:            list of gases to query. For possible values, see .gases .
                         Default: query for all gases.
:param batch_size:       number of variables to query in a single API query in the same batch to avoid internal
                         server errors. Larger queries are split automatically.
:param progress:         show a progress bar. Requires tqdm.
File:      ~/work/read_di_unfccc/read_di_unfccc.py
Type:      method

In [15]:
# Fine-grained control is possible
# Ex. query for german net emissions/removals of CO₂ in the category 5.A.1.a
# You have to provide categories and measures using IDs, because names are not necessarily unique
r.annex_one_reader.query(party_codes=['DEU'], category_ids=[9839], gases=['CO₂'], measure_ids=[10460])

,index,party,category,classification,measure,gas,unit,year,numberValue,stringValue
0,1,DEU,5.A.1.a Anaerobic,Total for category,Net emissions/removals,CO₂,kt,1990,None,NA
1,2,DEU,5.A.1.a Anaerobic,Total for category,Net emissions/removals,CO₂,kt,1991,None,NA
2,3,DEU,5.A.1.a Anaerobic,Total for category,Net emissions/removals,CO₂,kt,1992,None,NA
3,4,DEU,5.A.1.a Anaerobic,Total for category,Net emissions/removals,CO₂,kt,1993,None,NA
4,5,DEU,5.A.1.a Anaerobic,Total for category,Net emissions/removals,CO₂,kt,1994,None,NA
5,6,DEU,5.A.1.a Anaerobic,Total for category,Net emissions/removals,CO₂,kt,1995,None,NA
6,7,DEU,5.A.1.a Anaerobic,Total for category,Net emissions/removals,CO₂,kt,1996,None,NA
7,8,DEU,5.A.1.a Anaerobic,Total for category,Net emissions/removals,CO₂,kt,1997,None,NA
8,9,DEU,5.A.1.a Anaerobic,Total for category,Net emissions/removals,CO₂,kt,1998,None,NA
9,10,DEU,5.A.1.a Anaerobic,Total for category,Net emissions/removals,CO₂,kt,1999,None,NA
10,11,DEU,5.A.1.a Anaerobic,Total for category,Net emissions/removals,CO₂,kt,2000,None,NA
11,12,DEU,5.A.1.a Anaerobic,Total for category,Net emissions/removals,CO₂,kt,2001,None,NA
12,13,DEU,5.A.1.a Anaerobic,Total for category,Net emissions/removals,CO₂,kt,2002,None,NA
13,14,DEU,5.A.1.a Anaerobic,Total for category,Net emissions/removals,CO₂,kt,2003,None,NA
14,15,DEU,5.A.1.a Anaerobic,Total for category,Net emissions/removals,CO₂,kt,2004,None,NA
15,16,DEU,5.A.1.a Anaerobic,Total for category,Net emissions/removals,CO₂,kt,2005,None,NA
16,17,DEU,5.A.1.a Anaerobic,Total for category,Net emissions/removals,CO₂,kt,2006,None,NA
17,18,DEU,5.A.1.a Anaerobic,Total for category,Net emissions/removals,CO₂,kt,2007,None,NA
18,19,DEU,5.A.1.a Anaerobic,Total for category,Net emissions/removals,CO₂,kt,2008,None,NA
19,20,DEU,5.A.1.a Anaerobic,Total for category,Net emissions/removals,CO₂,kt,2009,None,NA
20,21,DEU,5.A.1.a Anaerobic,Total for category,Net emissions/removals,CO₂,kt,2010,None,NA
21,22,DEU,5.A.1.a Anaerobic,Total for category,Net emissions/removals,CO₂,kt,2011,None,NA
22,23,DEU,5.A.1.a Anaerobic,Total for category,Net emissions/removals,CO₂,kt,2012,None,NA
23,24,DEU,5.A.1.a Anaerobic,Total for category,Net emissions/removals,CO₂,kt,2013,None,NA
24,25,DEU,5.A.1.a Anaerobic,Total for category,Net emissions/removals,CO₂,kt,2014,None,NA
25,26,DEU,5.A.1.a Anaerobic,Total for category,Net emissions/removals,CO₂,kt,2015,None,NA
26,27,DEU,5.A.1.a Anaerobic,Total for category,Net emissions/removals,CO₂,kt,2016,None,NA
27,28,DEU,5.A.1.a Anaerobic,Total for category,Net emissions/removals,CO₂,kt,2017,None,NA
28,29,DEU,5.A.1.a Anaerobic,Total for category,Net emissions/removals,CO₂,kt,2018,None,NA
29,0,DEU,5.A.1.a Anaerobic,Total for category,Net emissions/removals,CO₂,kt,Base year,None,NA

In [24]:
'AFG' in r.non_annex_one_reader.parties['code'].values

True